package org.bookstore.bookstore.enums;

public enum GenreType {
    ACTION_ADVENTURE, HISTORY, CRIME, COMEDY, CLASSIC, FANTASY, FICTION, HORROR, MYSTERY, PARANORMAL, POETRY, ROMANCE,
    RELIGION, PHILOSOPHY, SCIENCE_FICTION, SPORTS, THRILLER, TRAVEL, YOUNG_ADULT, NON_FICTION;
}
